export enum CounterType {
  "BATCH" = "BATCH",
  "ORDER" = "ORDER",
  "DISPATCH" = "DISPATCH",
  "PACKAGE" = "PACKAGE",
  "SHIPMENT" = "SHIPMENT",
  "LOADING" = "LOADING",
  "ORDER_LOADING" = "ORDER_LOADING",
}
