export enum AllowedPermission {
  CREATE = "create",
  READ = "read",
  UPDATE = "update",
  DELETE = "delete",
  IMPORT = "import",
  EXPORT = "export",
}

export enum Modules {
  Dashboard = "Dashboard",
  Product = "Product",
  Order = "Order",
  Shipment = "Shipment",
  Loading = "Loading",
  Transport = "Transport",
  Brand = "Brand",
  MaterialCenter = "MaterialCenter",
  User = "User",
  Customer = "Customer",
  Profile = "Profile",
  Role = "Role",
  Bilty = "Bilty",
  Configuration = "Configuration",
  CustomerBeat = "CustomerBeat",
  CashReceipt = "CashReceipt",
}

export enum Features {
  Dashboard = "Dashboard",
  Product = "Product",
  Order = "Order",
  Dispatch = "Dispatch",
  OrderLoad = "Load",
  Shipment = "Shipment",
  Loading = "Loading",
  Transport = "Transport",
  Brand = "Brand",
  ItemGroup = "ItemGroup",
  BillSundry = "BillSundry",
  MaterialCenter = "MaterialCenter",
  User = "User",
  Customer = "Customer",
  Discount = "Discount",
  Profile = "Profile",
  Role = "Role",
  Bilty = "Bilty",
  Configuration = "Configuration",
  CustomerBeat = "CustomerBeat",
  CashReceipt = "CashReceipt",
  CustomerBeatSchedule = "CustomerBeatSchedule",
}
