export enum UserType {
  SUPERADMIN = "SUPERADMIN",
  ADMIN = "ADMIN",
  CUSTOMER = "CUSTOMER",
  WAREHOUSEMANAGER = "WAREHOUSEMANAGER",
  PACKAGER = "PACKAGER",
  LOADING_DRIVER = "LOADING_DRIVER",
  SALESMAN = "SALESMAN",
}
