import { IPermission } from "@repo/ui/types/permission";
import { Modules, Features } from "@repo/ui/enums/permission";

const permissions: Array<IPermission> = [
  {
    module: Modules.Dashboard,
    feature: Features.Dashboard,
    create: false,
    read: true,
    update: false,
    delete: false,
    import: false,
    export: false,
  },
  {
    module: Modules.Product,
    feature: Features.Product,
    create: true,
    read: true,
    update: true,
    delete: false,
    import: true,
    export: true,
  },
  {
    module: Modules.Product,
    feature: Features.ItemGroup,
    create: false,
    read: true,
    update: false,
    delete: false,
    import: true,
    export: false,
  },
  {
    module: Modules.Order,
    feature: Features.Order,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: true,
  },
  {
    module: Modules.Order,
    feature: Features.Dispatch,
    create: true,
    read: true,
    update: true,
    delete: false,
    import: false,
    export: false,
  },
  {
    module: Modules.Order,
    feature: Features.OrderLoad,
    create: true,
    read: true,
    update: true,
    delete: false,
    import: false,
    export: false,
  },
  {
    module: Modules.Shipment,
    feature: Features.Shipment,
    create: true,
    read: true,
    update: true,
    delete: false,
    import: false,
    export: false,
  },
  {
    module: Modules.Loading,
    feature: Features.Loading,
    create: true,
    read: true,
    update: true,
    delete: false,
    import: false,
    export: false,
  },
  {
    module: Modules.Transport,
    feature: Features.Transport,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: false,
  },
  {
    module: Modules.Brand,
    feature: Features.Brand,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: false,
  },
  {
    module: Modules.MaterialCenter,
    feature: Features.MaterialCenter,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: false,
  },
  {
    module: Modules.User,
    feature: Features.User,
    create: true,
    read: true,
    update: true,
    delete: false,
    import: false,
    export: false,
  },
  {
    module: Modules.Customer,
    feature: Features.Customer,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: true,
    export: true,
  },
  {
    module: Modules.Customer,
    feature: Features.Discount,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: false,
  },
  {
    module: Modules.Customer,
    feature: Features.BillSundry,
    create: false,
    read: true,
    update: false,
    delete: false,
    import: true,
    export: false,
  },
  {
    module: Modules.Profile,
    feature: Features.Profile,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: false,
  },
  {
    module: Modules.Bilty,
    feature: Features.Bilty,
    create: true,
    read: true,
    update: false,
    delete: false,
    import: false,
    export: false,
  },
  {
    module: Modules.Role,
    feature: Features.Role,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: false,
  },
  {
    module: Modules.Configuration,
    feature: Features.Configuration,
    create: false,
    read: true,
    update: true,
    delete: false,
    import: false,
    export: false,
  },
  {
    module: Modules.CustomerBeat,
    feature: Features.CustomerBeat,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: false,
  },
  {
    module: Modules.CustomerBeat,
    feature: Features.CustomerBeatSchedule,
    create: true,
    read: true,
    update: true,
    delete: true,
    import: false,
    export: false,
  },
  {
    module: Modules.CashReceipt,
    feature: Features.CashReceipt,
    create: true,
    read: true,
    update: true,
    delete: false,
    import: false,
    export: false,
  },
];

export default permissions;
